# Generated by Django 6.0.3 on 2026-04-09 14:09

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_category_tag_alter_blogpage_body_blogpage_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtail.fields.StreamField([('heading', 2), ('paragraph', 3), ('image', 4), ('gallery', 7), ('featured_page', 8), ('related_pages', 9), ('category_highlight', 10)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('h2', 'H2'), ('h3', 'H3'), ('h4', 'H4')]}), 2: ('wagtail.blocks.StructBlock', [[('text', 0), ('size', 1)]], {}), 3: ('wagtail.blocks.RichTextBlock', (), {}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 5: ('wagtail.blocks.CharBlock', (), {'required': False}), 6: ('wagtail.blocks.StructBlock', [[('image', 4), ('caption', 5)]], {}), 7: ('wagtail.blocks.ListBlock', (6,), {}), 8: ('wagtail.blocks.PageChooserBlock', (), {}), 9: ('wagtail.blocks.ListBlock', (8,), {}), 10: ('wagtail.snippets.blocks.SnippetChooserBlock', ('testapp.Category',), {})}),
        ),
    ]
