# Generated by Django 6.0.3 on 2026-04-09 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_alter_blogpage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpage',
            name='virtual',
            field=models.BooleanField(default=False),
        ),
    ]
